version: "2.1"
services:
  plex:
    image: plexinc/pms-docker
    container_name: home-theater
    environment:
      - PLEX_CLAIM= "NONE"
      - TZ="America/NewYork"
      - ADVERTISE_IP="YOURIPADDRESS:32400/"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - /Users/jostmann/Desktop/home-media-server/config:/config
      - /Users/jostmann/Desktop/home-media-server/tv:/tv
      - /Users/jostmann/Desktop/home-media-server/movies:/movies
      - /Users/jostmann/Desktop/home-media-server/data:/data
      - /Users/jostmann/Desktop/home-media-server/transcode:/transcode
    restart: unless-stopped